### PR TITLE
Add pdf.js annotation thumbnails to mini collection

### PR DESCRIPTION
**Pull request by nikolas**
Screenshot_2021-10-28_15-02-24

### CODE REVIEW

**Review by sdreher — COMMENTED** [review]
Reviewed code & ran live in my dev environment. The functionality is looking good to me.

I am seeing one issue that's again related to the height of the pdf viewer. Within the mini collection space, the viewer is overlaying the accordion links in subsequent selections. I think this image shows what's happening 
Screen Shot 2021-11-01 at 11 19 04 AM

**Comment by sdreher** [comment]
Excellent. That fixed it.

**Comment by nikolas** [comment]
I didn't do anything! Likely that bug still exists, thanks for noting it.

**Comment by nikolas** [comment]
I unassigned and re-assigned you here by accident.

**Pull request merged**
