### PR TITLE
Run lettuce tests on travis

### PR DESCRIPTION
**Pull request by nikolas**

### CODE REVIEW

**Comment by sdreher** [comment]
note: I'm forcing a few Travis rebuilds to ensure the last success wasn't just timing luck.

**Comment by sdreher** [comment]
@nikolas - this appears stable to me. (Though Selenium inherently has timing issues.) Do you want to take a look at the changes and merge?

**Comment by nikolas** [comment]
Looks good, I'll merge this, but I am still getting this error when running `make harvest` locally. But when I run this test alone with `./manage.py harvest mediathread/projects/features/composition.feature -d --settings=mediathread.settings_test -s 1`, it passes.
```
 Scenario: composition.feature 1. Instructor creates composition 
 # mediathread/projects/features/composition.feature:3                                                                                                               # terrain.py:71  Given I am test_instructor in Sample Course                                    
Given I am test_instructor in Sample Course 
# terrain.py:110
Given there are no projects  
# mediathread/projects/    Given there are no projects
# mediathread/projects/features/project-steps.py:10

File "/home/nnyby/src/mediathread/ve/local/lib/python2.7/site-packages/django/db/backends/sqlite3/base.py", line 485, in execute
        return Database.Cursor.execute(self, query, params)
    OperationalError: attempt to write a readonly database
```

**Comment by sdreher** [comment]
Do all the other tests pass?

**Comment by nikolas** [comment]
I'm not sure, I'll try it without `--failfast` now.. it takes a while.

**Comment by nikolas** [comment]
Here's my results from a local `make harvest` run:
```
Test Suite Summary:
4 features (2 passed)
28 scenarios (24 passed)
763 steps (4 failed, 147 skipped, 612 passed)

List of failed scenarios:
  Scenario: composition.feature 1. Instructor creates composition                                                                      
# mediathread/projects/features/composition.feature:3
  Scenario: composition.feature 2. Student creates composition                                                                         
# mediathread/projects/features/composition.feature:61
  Scenario Outline: publishtoworld.composition.feature 1. Instructor creates public to world composition - verify visibility
# mediathread/projects/features/publishtoworld.composition.feature:3
  Scenario Outline: publishtoworld.composition.feature 1. Instructor creates public to world composition - verify visibility
# mediathread/projects/features/publishtoworld.composition.feature:3
```

**Pull request merged**
