### PR TITLE
:arrow_up: OpenLayers 2.13.1

### PR DESCRIPTION
**Pull request by nikolas**
So, it's not clear what version of OpenLayers mediathread is currently
on (`VERSION_NUMBER` is set to the value `$Revision$`), but based on the
git history in sherdjs (the last update was around mid-2013), it appears it's somewhere around 2.x. I've
updated this to the most recent version available for 2.x: 2.13.1.

OpenLayers 2.x isn't compatible with jQuery 3.x, likely because of
something trivial. So we'll have to get to at least openlayers 3 to use
jQuery 3.

2018-02-01-133713_805x464_scrot

### CODE REVIEW

**Comment by nikolas** [comment]
Hmmm, after many retries, it looks like the harvest1 test suite is consistently failing here. I'll investigate.

**Comment by nikolas** [comment]
Hmmm.. this is pretty hard to debug, without being able to run these harvest tests locally. Looks like there's a persistent failure in the Onomy section, which doesn't make sense - this isn't using OpenLayers.

```
    And confirm the onomy import                                      # mediathread/taxonomy/features/taxonomy-steps.py:190
    And confirm the onomy import                                      # mediathread/taxonomy/features/taxonomy-steps.py:190
    Then there is a "Black" term                                      # mediathread/taxonomy/features/taxonomy-steps.py:167
    Then there is a "Black" term                                      # mediathread/taxonomy/features/taxonomy-steps.py:167
    Traceback (most recent call last):
      File "/home/travis/build/ccnmtl/mediathread/ve/lib/python2.7/site-packages/lettuce/core.py", line 144, in __call__
        ret = self.function(self.step, *args, **kw)
      File "/home/travis/build/ccnmtl/mediathread/mediathread/taxonomy/features/taxonomy-steps.py", line 170, in there_is_a_name_term
        wait.until(visibility_of_element_located((By.CSS_SELECTOR, selector)))
      File "/home/travis/build/ccnmtl/mediathread/ve/lib/python2.7/site-packages/selenium/webdriver/support/wait.py", line 80, in until
        raise TimeoutException(message, screen, stacktrace)
    TimeoutException: Message: 
    Screenshot: available via screen
```

**Comment by sdreher** [comment]
I can run `harvest` locally. I'll take a look.

**Comment by sdreher** [comment]
This breaks locally for me. I'll dig deeper into this.

**Comment by nikolas** [comment]
nice catch! looks like this is passing now.

**Pull request merged**
